holder/urls.py
from django.urls import path
from . import views

app_name = 'holder'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
]

land/urls.py
from django.urls import path
from . import views

app_name = 'land'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('posts/', views.posts, name='posts'),
    path('services/', views.services, name='services'),
    path('contacts/', views.contacts, name='contacts'),
    path('comments/', views.comments, name='comments'),
    path('info/', views.info, name='info'),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('abhi/', admin.site.urls),
    path('', include('land.urls', namespace='land')),
    path('holder/', include('holder.urls', namespace='holder')),
]

holder/models.py
from django.db import models

# Create your models here.


class Holder(models.Model):
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=20)

    def __str__(self):
        return self.email

land/models.py
from django.db import models

# Create your models here.


class Comments(models.Model):
    email = models.EmailField(max_length=100)
    report = models.TextField()

    def __str__(self):
        return self.email

holder/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import Holder


# Create your views here.


def signin(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        pwd = request.POST.get('pwd')

        try:
            a = Holder.objects.get(email=email).password

            if pwd == a:
                return HttpResponseRedirect("/")
            else:
                return render(request, 'holder/signin.html')
        except:
            return render(request, 'holder/signin.html')
    else:
        return render(request, 'holder/signin.html')


def signup(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        pwd = request.POST.get('pwd')
        cpwd = request.POST.get('cpwd')

        if email != "" and pwd != "" and cpwd != "" and pwd == cpwd:
            hdr = Holder(email=email, password=pwd)
            hdr.save()
        else:
            return render(request, 'holder/signup.html')
        return HttpResponseRedirect("/")
    else:
        return render(request, 'holder/signup.html')

land/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import Comments

# Create your views here.


def index(request):
    return render(request, 'land/index.html')


def posts(request):
    return render(request, 'land/posts.html')


def about(request):
    return render(request, 'land/about.html')


def services(request):
    return render(request, 'land/services.html')


def contacts(request):
    return render(request, 'land/contacts.html')


def info(request):
    return render(request, 'land/info.html')


def comments(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        report = request.POST.get('report')

        if email != "" and report != "":
            cmnt = Comments(email=email, report=report)
            cmnt.save()
        else:
            return render(request, 'land/index.html')

        return HttpResponseRedirect("/")
    else:
        return render(request, 'land/index.html')

holder/templates/holder/signin.html
{% extends 'land/base.html' %}
{% block content %}
{% load static %}

<!-- starting of sign in  page  -->
<main class="container-fluid bg-dark m-0 p-1">
    <!-- the dialouge space for the sign in  page  -->
    <section class="container-fluid bg-dark text-danger text-center p-0 m-0">
        <h5 class="fw-bold m-0 p-0 ">
            Welcome Back 
        </h5>
    </section>

    <!-- heading of the sign in  section page  -->
    <section class="container-fluid bg-dark text-warning text-center p-0 m-0">
        <h1 class="fw-bold text-capitalize m-0 p-0 ">Sign In</h1>
    </section>

    <!-- alert section of the signin page  -->
    <section class="container-fluid bg-dark text-center p-1 px-md-5 m-0">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>
                If input the Sign In form are invalid, your are redirected to same page again and again 
                until you enter the required. In case of valid input will take you to next step.
            </strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </section>

    <!-- sign in form for the abhicode website  -->
    <section class="container-fluid m-0 p-0 bg-dark">
        <div class="row d-flex justify-content-center container-fluid m-0 p-2">
            <div class="col-md-6 container-fluid m-0 p-2 text-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                </svg>
            </div>
            <div class="col-md-6 container-fluid m-0 p-0">
                <form action="{% url 'holder:signin' %}" method="POST" class="container-fluid m-0 p-0 px-md-5">
                    {% csrf_token %}
                    <div class="mb-3 px-md-5">
                      <label for="exampleInputEmail1" class="form-label text-info fw-bold">Email Address:</label>
                      <input type="email" name="email" class="form-control bg-dark text-success fw-bold" id="exampleInputEmail1" aria-describedby="emailHelp">
                      
                    </div>
                    <div class="mb-3 px-md-5">
                      <label for="exampleInputPassword1" class="form-label text-info fw-bold">Password: </label>
                      <input type="password" name="pwd" class="form-control bg-dark text-success fw-bold" id="exampleInputPassword1">
                    </div>
                    
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary fw-bold">Sign In</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
</main>



{% endblock %}

land/templates/land/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- title of the website on browser tab -->
    <title>AbhiCode | peer to peer </title>
    <!-- favicon for the page -->
    <link rel="shortcut icon" href="{% static 'land/logo.jpg' %}" type="image/x-icon" />
    <style>
      #stick {
        position: sticky;
        left: 0;
        top: 0;
        z-index: 1;
      }
    </style>
  </head>
  <body class="bg-dark text-light">
      <!-- all the code of the page goes here  -->

    <header class="container-fluid m-0 p-0 " id="stick">
      

      <!-- second one -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand text-light fs-3 fw-bold p-0">
            <img src="{% static 'land/logo.jpg' %}" alt="logo" width="35" height="35" class="  rounded-circle d-inline-block align-text-center ">
            AbhiCode
          <a/>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 pt-2">
              <li class="nav-item w-100 text-center">
                <a class="nav-link active text-info fw-bold" href="{% url 'land:index' %}">Home</a>
              </li>
              <li class="nav-item w-100 text-center">
                <a class="nav-link active text-info fw-bold" href="{% url 'land:posts' %}">Posts</a>
              </li>
              <li class="nav-item w-100 text-center">
                <a class="nav-link active text-info fw-bold" href="{% url 'land:about' %}">About</a>
              </li>
              <li class="nav-item w-100 text-center">
                <a class="nav-link active text-info fw-bold" href="{% url 'land:services' %}">Services</a>
              </li>
              <li class="nav-item w-100 text-center">
                <a class="nav-link active text-info fw-bold" href="{% url 'land:contacts' %}">Contacts</a>
              </li>
              
            </ul>
            <div class="d-flex justify-content-center">
              <!-- <input class="form-control me-2" type="search" placeholder="type here..." aria-label="Search"> -->
              <a href="{% url 'holder:signin' %}" type="button" class="btn btn-outline-primary btn-sm mx-1 fw-bold ">
                Sign In
              </a>
              <a href="{% url 'holder:signup' %}" type="button" class="btn btn-outline-primary btn-sm mx-1 fw-bold">
                Sign Up
              </a>
              
              
            </div>
          </div>
        </div>
      </nav>
    </header>

    <!-- think first code next  -->

    {% block content %}
    {% endblock %}

    <!-- the footer of the web page  -->
    
    <footer class="container-fluid p-2 m-0 bg-dark text-center">
      <div class="container  p-0 text-center text-secondary fw-bold">
        copyrights &copy;
        <script>
          const d = new Date();
          document.write(d.getFullYear());
        </script>
      </div>
      <div class="container p-0 text-center text-secondary fw-bold">
        All Rights Reserved
      </div>
      <div class="m-0 container-fluid row d-flex justify-content-center">
        <div class="m-0 col-md-3 text-center fw-bold text-success">AbhiCode</div>
        <div class="m-0 col-md-3 text-center fw-bold text-success">gabhishekji123@gmail.com</div>
        <div class="m-0 col-md-3 text-center fw-bold text-success">ABHISHEK GEDELA</div>
      </div>
      <div class="container">
        <!-- linked in logo  -->
        <a target="_blank" href="https://www.linkedin.com/in/abhishek-gedela-7b06511aa/" class="text-decoration-none">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin text-info" viewBox="0 0 16 16">
            <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
          </svg>
        </a>
        <!-- git hub logo  -->
        <a target="_blank" href="https://github.com/abhishekgedelacode" class="text-decoration-none">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github text-warning" viewBox="0 0 16 16">
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
          </svg>
        </a>
        <!-- youtube icon  -->
        <a target="_blank" href="https://www.youtube.com/channel/UCoOZmJyg8TnQuqAeNPaAPKA" class="text-decoration-none">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-youtube text-danger" viewBox="0 0 16 16">
            <path d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z"/>
          </svg>
        </a>
        <!-- facebook logo  -->
        <a target="_blank" href="https://www.facebook.com/abhishek.gedela/" class="text-decoration-none">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook text-primary" viewBox="0 0 16 16">
            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
          </svg>
        </a>
        <!-- instagram logo  -->
        <a target="_blank" href="https://www.instagram.com/abhishekgedela/" class="text-decoration-none">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram text-danger" viewBox="0 0 16 16">
            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
          </svg>
        </a>
      </div>
    </footer>
    

      <!-- end of my code  -->
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

land/templates/land/index.html
{% extends 'land/base.html' %}
{% block content %}
{% load static %}

  <div class="container-fluid text-warning text-center p-0 m-0">
    <h5 class="fw-bold text-capitalize m-0 p-0 ">think first code next</h5>
  </div>

  <!-- this is cover photo for the page  -->
  <div class="container-fluid  m-0 p-0">
      
    <img src="{% static 'land/coverpic.png' %}"  class="img-fluid m-0 p-0 " alt="">
  </div>

  <!-- cards of the videos , blogs and notes  -->
  <div class="container-fluid  m-0 p-1">
    <h1 class="container fw-bold text-center text-warning">
      *** We Provide ***
    </h1>
    <div class="row d-flex justify-content-around m-0 p-2">
      <!-- this is video section topic -->
      <div
        class="col-md-3 shadow-lg card border-0 p-0 m-2 bg-dark text-capitalize text-center"
      >
        <div class="card-header border border-3 border-success">
          <h4 class="card-title fw-bold text-success">
            videos
          </h4>
        </div>
        <div class="card-body border border-3 border-success">
          <p class="card-text fw-bold text-success">
            watch video tutorials 
          </p>
        </div>
        <div class="card-footer border border-success border-3">
          <a
            href="./gitpage.html"
            class="btn btn-outline-success btn-sm fw-bold"
            >watch</a
          >
        </div>
      </div>
      <!-- this is second topic -->
      <!-- this is bolg section topic -->
      <div
        class="col-md-3 shadow-lg card border-0 p-0 m-2 bg-dark text-capitalize text-center"
      >
        <div class="card-header border border-3 border-danger">
          <h4 class="card-title fw-bold text-danger">
            blogs
          </h4>
        </div>
        <div class="card-body border border-3 border-danger">
          <p class="card-text fw-bold text-danger">
            enjoy reading blogs 
          </p>
        </div>
        <div class="card-footer border border-danger border-3">
          <a
            href="./gitpage.html"
            class="btn btn-outline-danger btn-sm fw-bold"
            >explore</a
          >
        </div>
      </div>
      <!-- this is notes topic -->
      <div
        class="col-md-3 shadow-lg card border-0 p-0 m-2 bg-dark text-capitalize text-center"
      >
        <div class="card-header border border-3 border-info">
          <h4 class="card-title fw-bold text-info">
            notes
          </h4>
        </div>
        <div class="card-body border border-3 border-info">
          <p class="card-text fw-bold text-info">
            material and soft copies 
          </p>
        </div>
        <div class="card-footer border border-info border-3">
          <a
            href="./gitpage.html"
            class="btn btn-outline-info btn-sm fw-bold"
            >read</a
          >
        </div>
      </div>  
      
      <!-- this for the gallory setup  -->
      <div
        class="col-md-3 shadow-lg card border-0 p-0 m-2 bg-dark text-capitalize text-center"
      >
        <div class="card-header border border-3 border-success">
          <h4 class="card-title fw-bold text-success">
            gallery
          </h4>
        </div>
        <div class="card-body border border-3 border-success">
          <p class="card-text fw-bold text-success">
            take a look 
          </p>
        </div>
        <div class="card-footer border border-success border-3">
          <a
            href="./gitpage.html"
            class="btn btn-outline-success btn-sm fw-bold"
            >glance</a
          >
        </div>
      </div>

      <!-- this for glossary setup   -->
      <div
        class="col-md-3 shadow-lg card border-0 p-0 m-2 bg-dark text-capitalize text-center"
      >
        <div class="card-header border border-3 border-info">
          <h4 class="card-title fw-bold text-info">
            glossary
          </h4>
        </div>
        <div class="card-body border border-3 border-info">
          <p class="card-text fw-bold text-info">
            let us define
          </p>
        </div>
        <div class="card-footer border border-info border-3">
          <a
            href="./gitpage.html"
            class="btn btn-outline-info btn-sm fw-bold"
            >learn</a
          >
        </div>
      </div>
      <!-- end of the topics  -->
    </div>
  </div>

  <!-- setup for follow, join and support  -->
  <div class="container-fluid  m-0 p-1">
    <div class="row d-flex justify-content-center m-0 p-2">
      <div class="card bg-primary col-md-3 shadow-lg text-center">
        <div class="card-header">
          <a href="{% url 'land:info' %}" class="text-decoration-none text-light fw-bold">Follow Us</a>
        </div>
      </div>
      <div class="card bg-warning col-md-3 shadow-lg text-center">
        <div class="card-header">
          <a href="{% url 'land:info' %}" class="fw-bold text-decoration-none text-success">Join Us</a>
        </div>
      </div>
      <div class="card bg-success col-md-3 shadow-lg text-center">
        <div class="card-header">
          <a class="fw-bold text-decoration-none text-light" href="{% url 'land:info' %}">Support Us</a>
        </div>
      </div>
    </div>
  </div>

  <!-- here:  vision and mission of the website using modals  -->
  <div class="container-fluid m-0 p-1">
    <div class="row d-flex justify-content-center m-0 p-2">
      <button type="button" class="fw-bold col-5 btn btn-outline-danger border-3 m-1" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Vision
      </button>
      <button type="button" class="fw-bold col-5 btn btn-outline-danger border-3 m-1" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Mission
      </button>
    </div>
  </div>
  <!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog border border-light bg-dark">
    <div class="modal-content bg-dark">
      <div class="modal-header bg-dark">
        <h5 class="modal-title text-info strong fw-bold  text-info" id="exampleModalLabel">Vision &amp; Mission</h5>
        <button type="button" class="btn-close bg-danger" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-light">
        <div>
          Our <span class="strong text-success fw-bold">vision</span> is to build and connect a gigantic 
          network of peers as an ocean and we are only a few drops.
        </div>
        <div>
          Our <span class="strong text-success fw-bold">mission</span> is to emerge as a leading 
          nonprofit community that helps peers to update and upgrade themselves.
        </div>
      </div>
      <div class="modal-footer d-flex justify-content-center">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

<!-- comments goes here that is a simple form  -->
<div class="container px-md-5 ">
  <h4 class="container fw-bold text-center text-info bg-dark">
    *** Notify Us ***
  </h4>
  <form action="{% url 'land:comments' %}" method="POST" class="container px-md-5">
    {% csrf_token %}
    <div class="mb-3 px-md-5">
      <label for="exampleFormControlInput1" class="form-label text-success">Email address: </label>
      <input type="email" class="form-control fw-bold text-warning bg-dark" id="exampleFormControlInput1" name="email" placeholder="emailaddress@domain.com">
    </div>
    <div class="mb-3 px-md-5">
      <label for="exampleFormControlTextarea1" class="form-label text-success">Report: </label>
      <textarea class="form-control fw-bold text-warning bg-dark " id="exampleFormControlTextarea1" name="report" rows="3" placeholder="write the message you want to inform us..."></textarea>
    </div>
    <div class="text-center">
      <button type="submit" class="btn btn-success btn-sm fw-bold">Submit</button>
    </div>
  </form>
</div>



  
{% endblock %}

land/templates/land/info.html
{% extends 'land/base.html' %}
{% block content %}
{% load static %}

<!-- starting of info page  -->
<main class="container-fluid bg-dark m-0 p-1">
    <!-- the dialouge space for the info page  -->
    <section class="container-fluid bg-dark text-danger text-center p-0 m-0">
        <h5 class="fw-bold m-0 p-0 ">
            Walk Together
        </h5>
    </section>

    <!-- heading of the info section page  -->
    <section class="container-fluid bg-dark text-warning text-center p-0 m-0">
        <h1 class="fw-bold text-capitalize m-0 p-0 ">our team</h1>
    </section>
</main>



{% endblock %}